package com.bloodpressuremonitor.group4.csc325_group4.model;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class User {

    private String id;
    private String firstName;
    private String lastName;
    private String email;
    private LocalDate dateOfBirth;
    private int age;
    private List<BloodPressureReading> BPHistory;

    //called when an existing user is loaded from database
    public User(String firstName, String lastName, String email, int age, LocalDate dateOfBirth, String id, List<BloodPressureReading> BPHistory) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.age = age;
        this.dateOfBirth = dateOfBirth;
        this.id = id;
        this.BPHistory = BPHistory;
    }

    //called when a new user is created
    public User(String firstName, String lastName, String email, int age, LocalDate dateOfBirth, String id) {
        this.id = id; //This ID should come from the ID generated by Firebase authentication when creating a user
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.age = age;
        this.dateOfBirth = dateOfBirth;
        BPHistory = new ArrayList<BloodPressureReading>();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public List<BloodPressureReading> getBPHistory() {
        return BPHistory;
    }

    @Override
    public String toString(){
        return "\nID: " + this.getId() + "\nName: " + this.getFirstName() + " "
                + this.getLastName() + "\nAge: " + this.getAge()
                + "\nDate of Birth: " + this.getDateOfBirth();
    }

}
