package com.bloodpressuremonitor.group4.csc325_group4.model;

import java.util.List;

public class User {

    private String id;
    private String firstName;
    private String lastName;
    private String email;
    private int age;
    private List<BloodPressureReading> BPHistory;

    public User(String firstName, String lastName, String email, int age,  String id) {
        this.id = id; //This ID should come from the ID generated by Firebase authentication when creating a user
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.age = age;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public List<BloodPressureReading> getBPHistory() {
        return BPHistory;
    }

}
